// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseAllSessions(): $CancellablePromise<void> {
    return $Call.ByID(3174477948);
}

export function CloseSFTP(id: string): $CancellablePromise<void> {
    return $Call.ByID(2486276215, id);
}

export function CloseSSH(id: string): $CancellablePromise<void> {
    return $Call.ByID(3049651332, id);
}

export function ConnectSFTP(hostID: string): $CancellablePromise<$models.SFTPConnectResult> {
    return $Call.ByID(1024773161, hostID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ConnectSSH(hostID: string): $CancellablePromise<$models.SessionState> {
    return $Call.ByID(2246636346, hostID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ConnectSSHWithSize(hostID: string, cols: number, rows: number): $CancellablePromise<$models.SessionState> {
    return $Call.ByID(333341575, hostID, cols, rows).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteHost(id: string): $CancellablePromise<$models.HostConfig[]> {
    return $Call.ByID(3991181311, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DeleteVault(id: string): $CancellablePromise<$models.VaultCredential[]> {
    return $Call.ByID(3411622271, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DownloadSFTP(id: string, remotePath: string, localDir: string): $CancellablePromise<void> {
    return $Call.ByID(2946642475, id, remotePath, localDir);
}

export function ExportLocalData(pathOut: string, passphrase: string): $CancellablePromise<$models.LocalTransferResult> {
    return $Call.ByID(3512999883, pathOut, passphrase).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetSyncConfig(): $CancellablePromise<$models.SyncConfig> {
    return $Call.ByID(3219954471).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ImportLocalData(pathIn: string, passphrase: string, replace: boolean): $CancellablePromise<$models.LocalTransferResult> {
    return $Call.ByID(2084156406, pathIn, passphrase, replace).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ImportSSHConfig(pathIn: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(3909273485, pathIn).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ImportVaultKeyFile(vaultID: string, keyPath: string): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(601603422, vaultID, keyPath).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Info(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(3943185810).then(($result: any) => {
        return $$createType9($result);
    });
}

export function InstallUpdate(asset: $models.ReleaseAsset): $CancellablePromise<string> {
    return $Call.ByID(3729456840, asset);
}

export function KnownHostsInfo(): $CancellablePromise<$models.KnownHostsView> {
    return $Call.ByID(2835436492).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListHosts(): $CancellablePromise<$models.HostConfig[]> {
    return $Call.ByID(3981090681).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListSFTP(id: string, path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(4251993159, id, path).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListVault(): $CancellablePromise<$models.VaultCredential[]> {
    return $Call.ByID(4118150970).then(($result: any) => {
        return $$createType5($result);
    });
}

export function LocalHome(): $CancellablePromise<string> {
    return $Call.ByID(35437922);
}

export function LocalList(path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(1818475213, path).then(($result: any) => {
        return $$createType12($result);
    });
}

export function LocalMkdir(localPath: string): $CancellablePromise<void> {
    return $Call.ByID(3542386220, localPath);
}

export function LocalVaultEncryptExisting(passphrase: string): $CancellablePromise<$models.LocalVaultStatus> {
    return $Call.ByID(2126800717, passphrase).then(($result: any) => {
        return $$createType13($result);
    });
}

export function LocalVaultLock(): $CancellablePromise<$models.LocalVaultStatus> {
    return $Call.ByID(236544844).then(($result: any) => {
        return $$createType13($result);
    });
}

export function LocalVaultStatus(): $CancellablePromise<$models.LocalVaultStatus> {
    return $Call.ByID(131352309).then(($result: any) => {
        return $$createType13($result);
    });
}

export function LocalVaultUnlock(passphrase: string): $CancellablePromise<$models.LocalVaultStatus> {
    return $Call.ByID(994748907, passphrase).then(($result: any) => {
        return $$createType13($result);
    });
}

export function MkdirAllSFTP(id: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1867533449, id, remotePath);
}

export function MkdirSFTP(id: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1769647076, id, remotePath);
}

export function OpenExternalURL(raw: string): $CancellablePromise<void> {
    return $Call.ByID(1691046826, raw);
}

export function PropertiesChecksumLocal(localPath: string, algo: string): $CancellablePromise<string> {
    return $Call.ByID(2829243487, localPath, algo);
}

export function PropertiesChecksumSFTP(id: string, remotePath: string, algo: string): $CancellablePromise<string> {
    return $Call.ByID(1438603269, id, remotePath, algo);
}

export function PropertiesChmodLocal(localPath: string, octal: string, recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(944293147, localPath, octal, recursive);
}

export function PropertiesChmodSFTP(id: string, remotePath: string, octal: string, recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(998302977, id, remotePath, octal, recursive);
}

export function PropertiesChownSFTP(id: string, remotePath: string, owner: string, group: string, recursive: boolean): $CancellablePromise<void> {
    return $Call.ByID(830098189, id, remotePath, owner, group, recursive);
}

export function PropertiesIdentityOptionsSFTP(id: string): $CancellablePromise<$models.IdentityOptions> {
    return $Call.ByID(2434159684, id).then(($result: any) => {
        return $$createType14($result);
    });
}

export function PropertiesLocalStat(localPath: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1256926828, localPath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function PropertiesSizeLocal(localPath: string): $CancellablePromise<number> {
    return $Call.ByID(243208917, localPath);
}

export function PropertiesSizeSFTP(id: string, remotePath: string): $CancellablePromise<number> {
    return $Call.ByID(353292303, id, remotePath);
}

export function PropertiesStatSFTP(id: string, remotePath: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1746257904, id, remotePath).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ReadTextLocal(localPath: string): $CancellablePromise<$models.TextFileContent> {
    return $Call.ByID(523661804, localPath).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ReadTextSFTP(id: string, remotePath: string): $CancellablePromise<$models.TextFileContent> {
    return $Call.ByID(3827275116, id, remotePath).then(($result: any) => {
        return $$createType15($result);
    });
}

export function RemoveLocal(localPath: string): $CancellablePromise<void> {
    return $Call.ByID(476650261, localPath);
}

export function RemoveSFTP(id: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(4076102223, id, remotePath);
}

export function RenameLocal(localPath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(378342271, localPath, newName);
}

export function RenameSFTP(id: string, remotePath: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(3364031845, id, remotePath, newName);
}

export function ResizeSSH(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(926277116, id, cols, rows);
}

export function SaveHost(h: $models.HostConfig): $CancellablePromise<$models.HostConfig[]> {
    return $Call.ByID(4277190849, h).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SaveSyncConfig(c: $models.SyncConfig): $CancellablePromise<$models.SyncConfig> {
    return $Call.ByID(2444515358, c).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SaveVault(v: $models.VaultCredential): $CancellablePromise<$models.VaultCredential[]> {
    return $Call.ByID(174913505, v).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ServerReleases(): $CancellablePromise<$models.ReleaseIndex> {
    return $Call.ByID(3269683007).then(($result: any) => {
        return $$createType16($result);
    });
}

export function SyncLogin(req: $models.SyncAccountRequest): $CancellablePromise<$models.SyncAccountResult> {
    return $Call.ByID(1194388022, req).then(($result: any) => {
        return $$createType17($result);
    });
}

export function SyncPull(passphrase: string): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(2820837906, passphrase).then(($result: any) => {
        return $$createType18($result);
    });
}

export function SyncPush(passphrase: string): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(2787723953, passphrase).then(($result: any) => {
        return $$createType18($result);
    });
}

export function TrustSSHHost(hostID: string, expectedFingerprint: string): $CancellablePromise<string> {
    return $Call.ByID(1019255812, hostID, expectedFingerprint);
}

export function UploadSFTP(id: string, localPath: string, remoteDir: string): $CancellablePromise<void> {
    return $Call.ByID(3646247986, id, localPath, remoteDir);
}

export function UploadSFTPChunk(id: string, uploadID: string, remotePath: string, offset: number, base64Data: string): $CancellablePromise<void> {
    return $Call.ByID(2140434423, id, uploadID, remotePath, offset, base64Data);
}

export function WriteSSH(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1169910401, id, data);
}

export function WriteTextLocal(localPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(374838165, localPath, content);
}

export function WriteTextSFTP(id: string, remotePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2354665423, id, remotePath, content);
}

// Private type creation functions
const $$createType0 = $models.SFTPConnectResult.createFrom;
const $$createType1 = $models.SessionState.createFrom;
const $$createType2 = $models.HostConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.VaultCredential.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.LocalTransferResult.createFrom;
const $$createType7 = $models.SyncConfig.createFrom;
const $$createType8 = $models.ImportResult.createFrom;
const $$createType9 = $models.AppInfo.createFrom;
const $$createType10 = $models.KnownHostsView.createFrom;
const $$createType11 = $models.FileEntry.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.LocalVaultStatus.createFrom;
const $$createType14 = $models.IdentityOptions.createFrom;
const $$createType15 = $models.TextFileContent.createFrom;
const $$createType16 = $models.ReleaseIndex.createFrom;
const $$createType17 = $models.SyncAccountResult.createFrom;
const $$createType18 = $models.SyncResult.createFrom;
