// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppInfo {
    "version": string;
    "configDir": string;
    "platform": string;
    "arch": string;
    "server": string;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("configDir" in $$source)) {
            this["configDir"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

export class FileEntry {
    "name": string;
    "path": string;
    "type": string;
    "size": number;
    "modified"?: number;
    "mode"?: string;
    "uid"?: number;
    "gid"?: number;
    "owner"?: string;
    "group"?: string;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class HostConfig {
    "id": string;
    "protocol"?: string;
    "name": string;
    "address": string;
    "port": number;
    "username": string;
    "authMode": string;
    "keyPath"?: string;
    "password"?: string;
    "privateKey"?: string;
    "passwordSaved"?: boolean;
    "privateKeySaved"?: boolean;
    "rdpEnabled"?: boolean;
    "rdpPort"?: number;
    "rdpUsername"?: string;
    "rdpPassword"?: string;
    "rdpPasswordSaved"?: boolean;
    "rdpDomain"?: string;
    "rdpWidth"?: number;
    "rdpHeight"?: number;
    "rdpScaleMode"?: string;
    "rdpKeyboardLayout"?: string;
    "vaultId"?: string;
    "tags": string[];
    "group"?: string;

    /** Creates a new HostConfig instance. */
    constructor($$source: Partial<HostConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("authMode" in $$source)) {
            this["authMode"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): HostConfig {
        const $$createField23_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField23_0($$parsedSource["tags"]);
        }
        return new HostConfig($$parsedSource as Partial<HostConfig>);
    }
}

export class IdentityOption {
    "name": string;
    "id": number;
    "label": string;

    /** Creates a new IdentityOption instance. */
    constructor($$source: Partial<IdentityOption> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IdentityOption instance from a string or object.
     */
    static createFrom($$source: any = {}): IdentityOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IdentityOption($$parsedSource as Partial<IdentityOption>);
    }
}

export class IdentityOptions {
    "owners": IdentityOption[];
    "groups": IdentityOption[];

    /** Creates a new IdentityOptions instance. */
    constructor($$source: Partial<IdentityOptions> = {}) {
        if (!("owners" in $$source)) {
            this["owners"] = [];
        }
        if (!("groups" in $$source)) {
            this["groups"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IdentityOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): IdentityOptions {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("owners" in $$parsedSource) {
            $$parsedSource["owners"] = $$createField0_0($$parsedSource["owners"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField1_0($$parsedSource["groups"]);
        }
        return new IdentityOptions($$parsedSource as Partial<IdentityOptions>);
    }
}

export class ImportResult {
    "ok": boolean;
    "message": string;
    "count": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

export class KnownHostsView {
    "path": string;
    "content": string;
    "count": number;

    /** Creates a new KnownHostsView instance. */
    constructor($$source: Partial<KnownHostsView> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnownHostsView instance from a string or object.
     */
    static createFrom($$source: any = {}): KnownHostsView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnownHostsView($$parsedSource as Partial<KnownHostsView>);
    }
}

export class LocalTransferResult {
    "ok": boolean;
    "message": string;
    "path": string;
    "count": number;
    "vaultCount": number;

    /** Creates a new LocalTransferResult instance. */
    constructor($$source: Partial<LocalTransferResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("vaultCount" in $$source)) {
            this["vaultCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTransferResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTransferResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTransferResult($$parsedSource as Partial<LocalTransferResult>);
    }
}

export class LocalVaultStatus {
    "configured": boolean;
    "unlocked": boolean;
    "encryptedValues": number;
    "plaintextSecrets": number;
    "message": string;

    /** Creates a new LocalVaultStatus instance. */
    constructor($$source: Partial<LocalVaultStatus> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("unlocked" in $$source)) {
            this["unlocked"] = false;
        }
        if (!("encryptedValues" in $$source)) {
            this["encryptedValues"] = 0;
        }
        if (!("plaintextSecrets" in $$source)) {
            this["plaintextSecrets"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalVaultStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalVaultStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalVaultStatus($$parsedSource as Partial<LocalVaultStatus>);
    }
}

export class RDPClipboardFileUpload {
    "name": string;
    "base64": string;
    "isDirectory"?: boolean;

    /** Creates a new RDPClipboardFileUpload instance. */
    constructor($$source: Partial<RDPClipboardFileUpload> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("base64" in $$source)) {
            this["base64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RDPClipboardFileUpload instance from a string or object.
     */
    static createFrom($$source: any = {}): RDPClipboardFileUpload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RDPClipboardFileUpload($$parsedSource as Partial<RDPClipboardFileUpload>);
    }
}

export class RDPDiagnostics {
    "sessionId": string;
    "bitmapUpdates": number;
    "compressedUpdates": number;
    "bytesApplied": number;
    "dirtyFrames": number;
    "fullFrames": number;
    "lastFrameAt": number;
    "lastPixelFormat": string;
    "colorDepths": { [_ in string]?: number };

    /** Creates a new RDPDiagnostics instance. */
    constructor($$source: Partial<RDPDiagnostics> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("bitmapUpdates" in $$source)) {
            this["bitmapUpdates"] = 0;
        }
        if (!("compressedUpdates" in $$source)) {
            this["compressedUpdates"] = 0;
        }
        if (!("bytesApplied" in $$source)) {
            this["bytesApplied"] = 0;
        }
        if (!("dirtyFrames" in $$source)) {
            this["dirtyFrames"] = 0;
        }
        if (!("fullFrames" in $$source)) {
            this["fullFrames"] = 0;
        }
        if (!("lastFrameAt" in $$source)) {
            this["lastFrameAt"] = 0;
        }
        if (!("lastPixelFormat" in $$source)) {
            this["lastPixelFormat"] = "";
        }
        if (!("colorDepths" in $$source)) {
            this["colorDepths"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RDPDiagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): RDPDiagnostics {
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("colorDepths" in $$parsedSource) {
            $$parsedSource["colorDepths"] = $$createField8_0($$parsedSource["colorDepths"]);
        }
        return new RDPDiagnostics($$parsedSource as Partial<RDPDiagnostics>);
    }
}

export class RDPRenderEndpoint {
    "sessionId": string;
    "url": string;
    "width": number;
    "height": number;

    /** Creates a new RDPRenderEndpoint instance. */
    constructor($$source: Partial<RDPRenderEndpoint> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RDPRenderEndpoint instance from a string or object.
     */
    static createFrom($$source: any = {}): RDPRenderEndpoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RDPRenderEndpoint($$parsedSource as Partial<RDPRenderEndpoint>);
    }
}

export class ReleaseAsset {
    "name": string;
    "url": string;
    "size": number;
    "sha256": string;

    /** Creates a new ReleaseAsset instance. */
    constructor($$source: Partial<ReleaseAsset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseAsset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseAsset($$parsedSource as Partial<ReleaseAsset>);
    }
}

export class ReleaseIndex {
    "version": string;
    "versions": ReleaseVersion[];
    "files": ReleaseAsset[];
    "changelog"?: string[];

    /** Creates a new ReleaseIndex instance. */
    constructor($$source: Partial<ReleaseIndex> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseIndex instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseIndex {
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField1_0($$parsedSource["versions"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        if ("changelog" in $$parsedSource) {
            $$parsedSource["changelog"] = $$createField3_0($$parsedSource["changelog"]);
        }
        return new ReleaseIndex($$parsedSource as Partial<ReleaseIndex>);
    }
}

export class ReleaseVersion {
    "version": string;
    "assets": ReleaseAsset[];
    "changelog"?: string[];

    /** Creates a new ReleaseVersion instance. */
    constructor($$source: Partial<ReleaseVersion> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseVersion {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField1_0($$parsedSource["assets"]);
        }
        if ("changelog" in $$parsedSource) {
            $$parsedSource["changelog"] = $$createField2_0($$parsedSource["changelog"]);
        }
        return new ReleaseVersion($$parsedSource as Partial<ReleaseVersion>);
    }
}

export class SFTPConnectResult {
    "id": string;
    "home": string;

    /** Creates a new SFTPConnectResult instance. */
    constructor($$source: Partial<SFTPConnectResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("home" in $$source)) {
            this["home"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPConnectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPConnectResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPConnectResult($$parsedSource as Partial<SFTPConnectResult>);
    }
}

export class SSHDataPayload {
    "sessionId": string;
    "data"?: string;
    "dataB64"?: string;
    "seq": number;

    /** Creates a new SSHDataPayload instance. */
    constructor($$source: Partial<SSHDataPayload> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHDataPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHDataPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHDataPayload($$parsedSource as Partial<SSHDataPayload>);
    }
}

export class SessionState {
    "id": string;
    "hostId": string;
    "title": string;
    "status": string;
    "startedAt": number;
    "error"?: string;

    /** Creates a new SessionState instance. */
    constructor($$source: Partial<SessionState> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("hostId" in $$source)) {
            this["hostId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionState instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionState($$parsedSource as Partial<SessionState>);
    }
}

export class SyncAccountRequest {
    "endpoint": string;
    "username": string;
    "password": string;
    "label"?: string;
    "totp"?: string;

    /** Creates a new SyncAccountRequest instance. */
    constructor($$source: Partial<SyncAccountRequest> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncAccountRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncAccountRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncAccountRequest($$parsedSource as Partial<SyncAccountRequest>);
    }
}

export class SyncAccountResult {
    "token": string;
    "account": string;
    "message"?: string;
    "error"?: string;
    "totpRequired"?: boolean;

    /** Creates a new SyncAccountResult instance. */
    constructor($$source: Partial<SyncAccountResult> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncAccountResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncAccountResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncAccountResult($$parsedSource as Partial<SyncAccountResult>);
    }
}

export class SyncConfig {
    "enabled": boolean;
    "endpoint": string;
    "account": string;
    "token"?: string;
    "tokenSaved"?: boolean;
    "includeKeys": boolean;
    "lastSync"?: number;
    "autoPassphrase"?: string;
    "autoPassphraseSaved"?: boolean;

    /** Creates a new SyncConfig instance. */
    constructor($$source: Partial<SyncConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }
        if (!("includeKeys" in $$source)) {
            this["includeKeys"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncConfig($$parsedSource as Partial<SyncConfig>);
    }
}

export class SyncResult {
    "ok": boolean;
    "message": string;
    "count": number;
    "vaultCount": number;

    /** Creates a new SyncResult instance. */
    constructor($$source: Partial<SyncResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("vaultCount" in $$source)) {
            this["vaultCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResult($$parsedSource as Partial<SyncResult>);
    }
}

export class TextFileContent {
    "path": string;
    "name": string;
    "content": string;
    "size": number;
    "modified"?: number;

    /** Creates a new TextFileContent instance. */
    constructor($$source: Partial<TextFileContent> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextFileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): TextFileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextFileContent($$parsedSource as Partial<TextFileContent>);
    }
}

export class VaultCredential {
    "id": string;
    "name": string;
    "username": string;
    "authMode": string;
    "password"?: string;
    "keyPath"?: string;
    "privateKey"?: string;
    "passwordSaved"?: boolean;
    "privateKeySaved"?: boolean;

    /** Creates a new VaultCredential instance. */
    constructor($$source: Partial<VaultCredential> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("authMode" in $$source)) {
            this["authMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultCredential instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultCredential {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultCredential($$parsedSource as Partial<VaultCredential>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = IdentityOption.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = ReleaseVersion.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ReleaseAsset.createFrom;
const $$createType7 = $Create.Array($$createType6);
